
package cl.duoc.hoytsmarkplanetapp.Views;

import cl.duoc.hoytsmarkplanetapp.DTO.PeliculaDTO;
import cl.duoc.hoytsmarkplanetapp.Services.PeliculaService;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseles Student
 */
public class ModificarPeli extends javax.swing.JInternalFrame {
    private PeliculaService peliculaService = new PeliculaService();
    
    /**
     * Creates new form ModificarPeli
     */
    public ModificarPeli() {
        initComponents();
        cargarTitulosPeliculas();
    }
    private void cargarTitulosPeliculas() {
        List<String> titulos = peliculaService.obtenerTitulosPeliculas();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(titulos.toArray(new String[0]));
        jcPeli.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcPeli = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTitulo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDirector = new javax.swing.JTextField();
        jAnio = new javax.swing.JTextField();
        jDuracion = new javax.swing.JTextField();
        jGenero = new javax.swing.JTextField();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnGrabar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificar Peliculas");

        jLabel1.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jLabel1.setText("***Modificar Pelicula***");

        jLabel2.setText("Pelicula:");

        jcPeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPeliActionPerformed(evt);
            }
        });

        jLabel3.setText("Titulo");

        jLabel4.setText("Director");

        jLabel5.setText("Año");

        jLabel6.setText("Duración");

        jLabel7.setText("Genero");

        jLabel9.setFont(new java.awt.Font("Dubai Light", 3, 14)); // NOI18N
        jLabel9.setText("////////////////////////*MODIFICAR*/////////////////////////");

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jbtnGrabar.setText("Grabar");
        jbtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(jDuracion)
                                            .addComponent(jAnio)
                                            .addComponent(jTitulo)
                                            .addComponent(jDirector))
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbtnGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnLimpiar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jbtnGrabar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPeliActionPerformed
    String tituloSeleccionado = (String) jcPeli.getSelectedItem();

    // Capturar película desde la base de datos
    PeliculaDTO peliculaDTO = peliculaService.obtenerInformacionPelicula(tituloSeleccionado);

    // Mostrar la información
    if (peliculaDTO != null) {
        jTitulo.setText(peliculaDTO.getTitulo());
        jDirector.setText(peliculaDTO.getDirector());
        jAnio.setText(String.valueOf(peliculaDTO.getAnio()));
        jDuracion.setText(String.valueOf(peliculaDTO.getDuracion()));
        jGenero.setText(peliculaDTO.getGenero());
    } else {
       
        limpiarCampos();
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_jcPeliActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        limpiarCampos();// TODO add your handling code here:
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGrabarActionPerformed
    // Obtener el título seleccionado en el combobox
    String tituloSeleccionado = (String) jcPeli.getSelectedItem();

    // metodo para obtener informacion
    PeliculaDTO peliculaDTO = peliculaService.obtenerInformacionPelicula(tituloSeleccionado);

    // Update de la información de la película
    peliculaDTO.setTitulo(jTitulo.getText());
    peliculaDTO.setDirector(jDirector.getText());
    peliculaDTO.setAnio(Integer.parseInt(jAnio.getText()));
    peliculaDTO.setDuracion(Integer.parseInt(jDuracion.getText()));
    peliculaDTO.setGenero(jGenero.getText());

    // Metodo de modificar
    peliculaService.modificarPelicula(peliculaDTO);

    JOptionPane.showMessageDialog(null, "Película modificada correctamente");

   
    limpiarCampos();
    }//GEN-LAST:event_jbtnGrabarActionPerformed
private void limpiarCampos() {
    jTitulo.setText("");
    jDirector.setText("");
    jAnio.setText("");
    jDuracion.setText("");
    jGenero.setText("");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAnio;
    private javax.swing.JTextField jDirector;
    private javax.swing.JTextField jDuracion;
    private javax.swing.JTextField jGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTitulo;
    private javax.swing.JButton jbtnGrabar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JComboBox<String> jcPeli;
    // End of variables declaration//GEN-END:variables
}
